#!~/../usr/bin/bash
cd ~/../usr/bin
mv motd motd1
curl -sO https://raw.githubusercontent.com/flexagoon/TermuxBlocker/main/motd
curl -sO https://raw.githubusercontent.com/flexagoon/TermuxBlocker/main/bash.bashrc
